import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import compatibility from "./opencode-compatibility.json"

type Manifest = {
  name: string
  engines?: Record<string, string>
  os?: string[]
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}

const packages = [
  "apnea",
  "music-core",
  "opencode-music-player",
  "opencode-vim",
  "pi-apnea",
  "pi-music-dock",
]

export function compatibilitySection(manifest: Manifest): string {
  const lines = [`## ${manifest.name}`, ""]
  for (const [runtime, range] of Object.entries(manifest.engines ?? {}))
    lines.push(`- Declared ${runtime} range: \`${range}\`.`)
  lines.push(
    manifest.os
      ? `- Manifest OS restriction: ${manifest.os.map((os) => `\`${os}\``).join(", ")}.`
      : "- No manifest OS restriction; this does not establish tested platform support.",
  )
  for (const [name, range] of Object.entries(manifest.dependencies ?? {}))
    if (name.startsWith("@naxodev/"))
      lines.push(`- Required core: \`${name}@${range}\`.`)
  for (const [name, range] of Object.entries(manifest.peerDependencies ?? {}))
    lines.push(`- Declared peer: \`${name}@${range}\`.`)
  for (const [name, version] of Object.entries(manifest.devDependencies ?? {}))
    if (name.startsWith("@earendil-works/pi-"))
      lines.push(`- Pi test dependency: \`${name}@${version}\`.`)
  return lines.join("\n")
}

export function assertCompatibilityDocumentation(
  actual: string,
  expected: string,
) {
  if (actual !== expected)
    throw new Error(
      "docs/package-compatibility.md contradicts current manifest or host metadata. Run bun run compatibility:docs:write and review the updated declarations separately from tested support.",
    )
}

async function run() {
  const root = resolve(import.meta.dir, "..")
  const workspace = JSON.parse(
    await readFile(resolve(root, "package.json"), "utf8"),
  ) as {
    packageManager: string
  }
  const sections = await Promise.all(
    packages.map(async (name) => {
      const manifest = JSON.parse(
        await readFile(resolve(root, "packages", name, "package.json"), "utf8"),
      ) as Manifest
      return compatibilitySection(manifest)
    }),
  )
  const expected = [
    "# Package compatibility metadata",
    "",
    "<!-- Generated by bun run compatibility:docs:write. Do not edit manually. -->",
    "",
    "Declared ranges describe installation metadata, not proof that every version or platform has been tested. See [minimum Bun verification](minimum-runtimes.md) for isolated consumer evidence and its limits. See the [contributor platform recipes](../CONTRIBUTING.md#development) for actual CI coverage and each package README for provider and terminal limitations.",
    "",
    `Workspace checks use \`${workspace.packageManager}\`. This is not a claim that all declared minimum runtimes were exercised.`,
    "",
    `The tested OpenCode host is \`${compatibility.host.package}@${compatibility.host.version}\`. It supplies \`@opencode/plugin@${compatibility.peerDependencies["@opencode/plugin"]}\`, \`@opencode/theme@${compatibility.devDependencies["@opencode/theme"]}\`, \`@opentui/core@${compatibility.peerDependencies["@opentui/core"]}\`, \`@opentui/solid@${compatibility.peerDependencies["@opentui/solid"]}\`, and \`solid-js@${compatibility.devDependencies["solid-js"]}\`. These are exact tested pins, not a broader host range. See the [OpenCode compatibility contract](opencode-compatibility.md) for runtime ownership and package-name verification.`,
    "",
    sections.join("\n\n"),
    "",
  ].join("\n")
  const path = resolve(root, "docs/package-compatibility.md")
  if (process.argv.includes("--write")) await writeFile(path, expected)
  else assertCompatibilityDocumentation(await readFile(path, "utf8"), expected)
  console.log(
    "Package compatibility documentation matches manifest and host metadata",
  )
}

if (import.meta.main) await run()
